// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDesk.Repository;

#nullable disable

namespace ServiceDesk.Repository.Migrations
{
    [DbContext(typeof(ServiceDeskDbContext))]
    [Migration("20260924061154_AddTicketSelfAssignment")]
    partial class AddTicketSelfAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceDesk.Core.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedEmployeeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssignedEmployeeUserId");

                    b.HasIndex("CustomerUserId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Core.Tickets.TicketHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedEmployeeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AssignedEmployeeUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Shell.Authentication.UserAccessProvision", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ActivationTokenHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId");

                    b.HasIndex("ActivationTokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAccessProvisions_ActivationTokenHash");

                    b.ToTable("UserAccessProvisions", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Shell.Authentication.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("ServiceDesk.Core.Tickets.Ticket", b =>
                {
                    b.HasOne("ServiceDesk.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceDesk.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceDesk.Core.Tickets.TicketHistory", b =>
                {
                    b.HasOne("ServiceDesk.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceDesk.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceDesk.Core.Tickets.Ticket", null)
                        .WithMany("History")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceDesk.Shell.Authentication.UserAccessProvision", b =>
                {
                    b.HasOne("ServiceDesk.Core.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ServiceDesk.Shell.Authentication.UserAccessProvision", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceDesk.Shell.Authentication.UserCredential", b =>
                {
                    b.HasOne("ServiceDesk.Core.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ServiceDesk.Shell.Authentication.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceDesk.Core.Tickets.Ticket", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
